image: node
stages:          # List of stages for jobs, and their order of execution
  - lint

lint-job:       # This job runs in the lint stage, which runs first.
  stage: lint
  tags:
    - shared-fi
  script:
    - npm install
    - npm install -g eslint
    - eslint --ignore-path .gitignore .
